name: http_logger
description: A logging middleware for Dart's http module.
version: 0.0.3
author: Gurleen Sethi <sarusethi@rocketmail.com>
homepage: http://www.github.com/gurleensethi

dependencies:
  http_middleware: "^0.0.5"

environment:
    sdk: ">=1.8.0 <2.0.0"